# Generated by Django 3.1.7 on 2021-02-27 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, verbose_name='slug')),
                ('question_text', models.TextField(verbose_name='question_text')),
                ('question_img', models.FileField(default=None, null=True, upload_to='', verbose_name='question_img')),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('open_text', 'Open Text')], max_length=50, verbose_name='question_type')),
                ('answer', models.CharField(max_length=15, verbose_name='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, verbose_name='slug')),
                ('schedule_date', models.DateTimeField(verbose_name='schedule_date')),
                ('end_date', models.DateTimeField(verbose_name='end_date')),
                ('is_public', models.BooleanField(default=False, verbose_name='is_public')),
                ('description', models.TextField(default=None, null=True, verbose_name='description')),
                ('time_per_question', models.PositiveSmallIntegerField(default=60, help_text='Time in seconds to be given per question for a quiz', verbose_name='time_per_question')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_quiz_created_by', related_query_name='quiz_quizs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_quiz_updated_by', related_query_name='quiz_quizs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakenQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='score')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is_correct')),
                ('answer', models.CharField(default=None, max_length=250, null=True, verbose_name='correct_solution')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('taken_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.takenquiz')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
